[package]
name = "sk"
version = "0.1.0"
authors = ["Andrei <thedoctor095@yahoo.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.5.0"
webbrowser = "0.8.12"
