[package]
name = "sk"
version = "0.1.3"
authors = ["Andrei <thedoctor095@yahoo.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
openai-api-rs = "5.2.4"
tokio = "1.42.0"
url = "2.5.4"
webbrowser = "1.0.3"
